# Generated by Django 3.2 on 2023-03-24 15:43

import cloudinary.models
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=users.models.NigerianPhoneNumberField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='EMS/user_profile_images/default_avatar_sanr5o.png', max_length=255, verbose_name='image'),
        ),
    ]
