# Generated by Django 3.2 on 2023-03-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230324_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Agent', 'Agent'), ('Prospective Tenant', 'Prospective Tenant'), ('Estate Manager', 'Estate Manager'), ('Estate Staff Member', 'Estate Staff Member')], max_length=19),
        ),
    ]
