# Generated by Django 3.2 on 2023-03-24 21:48

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=users.models.NigerianPhoneNumberField(max_length=10, unique=True),
        ),
    ]
