# Generated by Django 3.2 on 2023-03-25 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^\\d{1,25}$', 'Enter a valid account number.')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
