# Generated by Django 3.2 on 2023-03-29 02:20

import cloudinary.models
from django.db import migrations
import helper.views


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230325_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='EMS/user_profile_images/default_avatar_sanr5o.png', max_length=255, validators=[helper.views.validate_image], verbose_name='image'),
        ),
    ]
