# Generated by Django 3.2 on 2023-03-29 10:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='EMS/user_profile_images/default_avatar_sanr5o.png', max_length=255, verbose_name='image'),
        ),
    ]
