# Generated by Django 3.2 on 2023-03-29 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(help_text='Activate Tenancy')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rent', 'Rent'), ('other', 'Other')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly'), ('one-time', 'One-time')], max_length=10)),
                ('due_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial_payment_field', models.BooleanField(default=False, help_text='This fee is to be paid on first payment for property e.g. rent, deposit fee, caution fee, etc.')),
                ('is_published', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fee.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.fee')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.tenancy')),
            ],
            options={
                'unique_together': {('fee', 'tenancy')},
            },
        ),
    ]
