# Generated by Django 3.2 on 2023-03-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenancy',
            options={'verbose_name_plural': 'Tenancies'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='initial_payment_field',
            field=models.BooleanField(default=False, help_text='This fee is to be paid on first payment for property e.g. rent, cost to purchase property, deposit fee, caution fee, etc.'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='name',
            field=models.CharField(help_text='e.g. Rent, Property Purchase Cost, Caution Fee, Deposit Fee, Security Fee', max_length=255),
        ),
        migrations.AlterField(
            model_name='fee',
            name='recurring',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly'), ('one-time', 'One-time')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='type',
            field=models.CharField(choices=[('paymentForProperty', 'Cost to Purchase or Own Property'), ('rent', 'Rent'), ('other', 'Other')], max_length=18),
        ),
    ]
