# Generated by Django 3.2 on 2023-03-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_auto_20230329_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='initial_payment_field',
            new_name='initial_payment_fee',
        ),
    ]
