# Generated by Django 3.2 on 2023-04-21 04:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_rename_initial_payment_field_fee_initial_payment_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='fee_snapshot',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='percentage_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fee',
            name='initial_payment_fee',
            field=models.BooleanField(help_text='This fee is to be paid on first payment for property e.g. rent, cost to purchase property, deposit fee, caution fee, etc.'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='is_published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fee',
            name='recurring',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly'), ('one-time', 'One-time')], default='one-time', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fee.fee'),
        ),
    ]
