# Generated by Django 3.2 on 2023-04-27 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fee', '0005_feepayment_paid_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='fee_snapshot',
            new_name='fees_snapshot',
        ),
        migrations.RenameField(
            model_name='feepayment',
            old_name='percentage_charge',
            new_name='saas_percentage_charge',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feepayment',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='fees',
            field=models.ManyToManyField(to='fee.Fee'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reference',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('UP', 'Unprocessed'), ('CM', 'Completed')], default='UP', max_length=2),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Cancel Tenancy'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='paid_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='tenancy',
        ),
    ]
